### ISSUE TITLE
Error running pdal

### ISSUE THREAD

**Issue by zdila** [SmartForest-no/Point2tree#1]
Hello.

I have problem running the scripts on Debian linux. The problem seems to be with `Parallel` call which terminates the pdal process prematurely for some reason.

```
python nibio_preprocessing/convert_files_in_folder.py --input_folder 0 --output_folder out --out_file_type las --in_place --verbose
INFO:root:Converting files in place.
Searching for files in the input folder...
INFO:root:Found 2 files.
INFO:root:Found 1 files that can be converted.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 253.19it/s]
terminate called after throwing an instance of 'std::runtime_error'
  what():  screen width not a valid file descriptor
Aborted
INFO:root:Converted 1 files.
INFO:root:Deleted 1 files.
DONE
```

**Comment by maciekwielgosz** [comment]
Hi,
You may have problems with the platform or dependencies on your machine. To avoid this, I recommend to setup the container on you host machine using : https://github.com/SmartForest-no/Point2tree/tree/master/docker . Then proceed with the installation steps in the container. You should be able to log to the container using ssh and work inside of it.
