### ISSUE TITLE
Point2Tree results in empty segments files

### ISSUE THREAD

**Issue by narges-tk** [SmartForest-no/Point2tree#2]
Dear Point2Tree authors, 
I have run your proposed code for Point2Tree on the GitHub. I followed the provided instructions and ran it on Ubuntu and in the command line everything went well. However, the results are empty and I cannot find any specific result. May I please ask you to comment on that?
Thanks in advance & best regards,
Narges

**Comment by maciekwielgosz** [comment]
Please attach the log files. If you don't have the logs please run the code and log the results to '*.txt' file and put it here.

**Comment by stefp** [comment]
Also, could you please let us know what type of point clouds are you are feeding to the algorithm? The method is meant to be used with dense terrestrial laser scanning point clouds (TLS/MLS) and we do not know how it will work on other point clouds.

**Comment by stefp** [comment]
@narges-tk  I checked your point cloud and it seems that it is from an airborne platform and too sparse for the method to work. Our method is supposed to work either with MLS or TLS data.

**Comment by stefp** [comment]
Please try with a denser point cloud such as this 
![image](https://github.com/SmartForest-no/Point2tree/assets/5663984/cb285e7f-33f1-41b2-860f-b19f7a4b3226)

**Comment by narges-tk** [comment]
Many thanks for your replies.
