### ISSUE TITLE
Terminate called after throwing an instance of 'std::runtime_error'   what():  screen width not a valid file descriptor

### ISSUE THREAD

**Issue by th00tames1** [SmartForest-no/Point2tree#3]
Thank you for the excellent research.

When attempting to perform Semantic Segmentation with Ubuntu on WSL2, the following error is encountered:

![20230828_182410](https://github.com/SmartForest-no/Point2tree/assets/48465225/291f447e-547b-4ff9-af07-3417631c784b)

"terminate called after throwing an instance of 'std::runtime_error'
what(): screen width not a valid file descriptor
Aborted"

![20230828_182400](https://github.com/SmartForest-no/Point2tree/assets/48465225/daeeb483-33e6-4c9f-bbd0-266e3c9c2005)

Furthermore, if you place the point cloud in a directory and execute it, a 0kb .ply file containing nothing is generated. Why does this error occur? Is there a possible solution? I'm curious to know if this behavior is expected.

I look forward to your response.
HC Jeong

**Comment by stefp** [comment]
Hi Jeong,

one thing that perhaps was not very clear in the readme is that the input point clouds should be in a local reference system and not in UTM (in which case the code breaks). Did you input point clouds with X and Y coordinates in UTM?

Stefano

**Comment by maciekwielgosz** [comment]
@th00tames1 Please check if the mapping works. You can just run this line :  https://github.com/SmartForest-no/Point2tree/blob/834d32c26bb55ef9eab4e528fb7ac836792b210b/run_bash_scripts/sem_seg.sh#L85C141-L86C1 solo and see the output. If this breaks, than it's a problem which @stefp  mentioned above. I have already put this information to the repo. It is relatively easy to expend the code with the reference system conversion.

**Comment by peryitedess** [comment]
Hi,

I got the same issue running on Ubuntu 20.04 and the MLS point cloud is in a local reference system as it is collected using SLAM (if I am understanding right about your definition of a local reference system). 

Then, I run the nibio_preprocessing/convert_files_in_folder.py line by line and skip the Parallel function, it works fine to transfer to ply format. But it's hard to debug further. Could you give me any suggestions?

Cheers,
Perry
